version: "3.7"

services:
  php:
    build:
      context: ./php
    container_name: tests-php
    working_dir: /var/www
    restart: unless-stopped
    volumes:
      - ../:/var/www
    expose:
      - "9000"